### ISSUE TITLE
try breaks error messages

### ISSUE THREAD

**Issue by feuerbach** [ekmett/trifecta#28] opened 2014-04-03 13:58 UTC
This works as expected:
```
Prelude Text.Trifecta> parseTest (string "foo" >> string "bar") "foo bar"
(interactive):1:4: error: expected: "bar"
foo bar<EOF> 
   ^         
```

But if I add `try`:

```
Prelude Text.Trifecta> parseTest (try $ string "foo" >> string "bar") "foo bar"
(interactive):1:1: error: unspecified error
foo bar<EOF> 
^            
```

**Comment by nushio3** [comment] 2015-11-14 16:11
I believe my post is offtopic, but here's another way trifecta may produce `error: unspecified error` message.

```
var = some $ satisfy isAlphaNum
num = some $ satisfy isDigit
program =  var >>  num >>  return ()
main = parseTest program "foo!"
```
produces
```
(interactive):1:4: error: unspecified error
foo!<EOF> 
   ^
```

The unspecified error is because, `satisfy` cannot produce message from `Char -> Bool` .

If we change the above program
```
var = some $ (satisfy isAlphaNum <?> "alphanums")
num = some $ (satisfy isDigit <?> "digits")
program = var >> num >>  return ()
main = parseTest program "foo!"
```
we get useful messages.
```      
(interactive):1:4: error: expected: alphanums, digits
foo!<EOF> 
   ^      
```
Since google search for `trifecta unspecified error` lands on this page, my wish is fulfilled if this tip reaches to another poor helpless trifecta user that bewildered by the uninformative message....

Alternatively, we can start writing FAQs for trifecta?

**Comment by ekmett** [comment] 2015-11-14 18:38
i've turned on the wiki for this package:

https://github.com/ekmett/trifecta/wiki

If you want to write FAQ material that might act as a good home.

**Comment by ekmett** [comment] 2016-01-17 00:04
Closing this as this particular feature is working as intended. Though I'll create an issue for creating a separate `race` combinator.

**Closed by ekmett** 2016-01-17 00:04 UTC

**Comment by nushio3** [comment] 2016-01-17 06:40
Thank you @ekmett , I filled up some https://github.com/ekmett/trifecta/wiki/Tips-&-FAQs in the wiki page. Thank you for starting the wiki page, and I'm sorry for my late start on writing.
